### ISSUE TITLE
grasshoper - compiling error on aarch64/arm64

### ISSUE THREAD

**Issue by mareksoha** [curiefense/curiefense#919]
There is a bug with datatypes when compiling grasshoper with rustc:

error[E0308]: mismatched types
 --> curiefense/src/grasshopper.rs:55:38
  |
55 |       let c_v = CStr::from_ptr(v);
  |            -------------- ^ expected u8, found i8
  |            |
  |            arguments to this function are incorrect
  |
  = note: expected raw pointer *const u8
       found raw pointer *const i8

error[E0308]: mismatched types
 --> curiefense/src/grasshopper.rs:64:38
  |
64 |       let c_v = CStr::from_ptr(v);
  |            -------------- ^ expected `u8`, found `i8`
  |            |
  |            arguments to this function are incorrect
  |
  = note: expected raw pointer `*const u8`
       found raw pointer `*const i8`

It is present on architecture aarch64 (arm64) and it must be included in some of latest changes as it works in tags v1.4.0 and v1.5.0. It doesnt work with master tree. On AMD64 it compiles fine.

**Comment by bartavelle** [comment]
Sorry for the very late answer. It will not work anyway, because the library is not open source and is compiled for x86, so during the linking phase it will fail :(
